### ISSUE TITLE
example page will not work with IE11

### ISSUE THREAD

**Issue by jedie** [diafygi/webcrypto-examples#12]
Because of promise **.then()** usage. See also: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#Browser_compatibility

Maybe https://github.com/taylorhakes/promise-polyfill will help here?!?

**Comment by diafygi** [comment]
WebCryptoAPI requires supporting promises, and IE's use of `onerror` and `oncomplete` is very out of date. IE shouldn't work in the live table because it doesn't work with the spec.

**Comment by jedie** [comment]
Thanks for the info.

Seems that "Microsoft Edge" in windows 10 will support promise, see: https://msdn.microsoft.com/library/dn802826%28v=vs.94%29.aspx

Has anybody test the example page with edge?!?
