### ISSUE TITLE
collect results in Wiki ?!?

### ISSUE THREAD

**Issue by jedie** [diafygi/webcrypto-examples#15]
What's about to collect some result via screenshot (see #14 ) in the Wiki?!?

**Comment by jedie** [comment]
Hm. I didn't find a way to upload a image to the Github Wiki :(

Maybe just collect everything in the normal git repro?

**Comment by diafygi** [comment]
Not interested in maintaining a compatibility/results table. See http://caniuse.com/#feat=cryptography

**Comment by jedie** [comment]
http://caniuse.com/#feat=cryptography is nice, but you can not see which parts are supported and which not :(

See also: https://github.com/Fyrd/caniuse/issues/1759

**Comment by jedie** [comment]
I started https://github.com/jedie/WebCrypto-compatibility to collect some compatibility informations...

**Comment by diafygi** [comment]
Awesome!
