### ISSUE TITLE
IE11 shows errors on 'Live Table'

### ISSUE THREAD

**Issue by xadhatter** [diafygi/webcrypto-examples#22]
When I try to run your Live Table on IE11 I see a bunch of errors in the console:

`SCRIPT438: Object doesn't support property or method 'then'`
`webcrypto-examples (127,25)`
...

It looks like you are using Promises which IE11 does not support.  Perhaps a polyfill will help? https://github.com/jakearchibald/es6-promise

Thanks for the all the examples; very, very helpful!

**Comment by diafygi** [comment]
Sorry, these examples are only intended to test the spec implementation, not IE11's.
