### ISSUE TITLE
Good work, keep it up!

### ISSUE THREAD

**Issue by alokmenghrajani** [diafygi/webcrypto-examples#3]
Just wanted to drop a short note to say it's nice to see people documenting this API.

You might be interested to check out Google's unittests: https://chromium.googlesource.com/chromium/blink/+/master/LayoutTests/crypto/subtle/

And MS has some good docs, but outdated since they Web Crypto API changed after they implemented it:
https://msdn.microsoft.com/en-us/library/ie/dn302338%28v=vs.85%29.aspx

**Comment by diafygi** [comment]
Thanks!
