### ISSUE TITLE
Real working Web Cryptography API based lib - PKIjs

### ISSUE THREAD

**Issue by YuryStrozhevsky** [diafygi/webcrypto-examples#4]
Guys,
Now you do not want such simple and almost unusefull examples because in [PKIjs](https://github.com/GlobalSign/PKI.js) we got real using of almost all Web Cryptography API algorithm making real PKI / CMS data (certificates, CRL, PKCS#10, OCSP, TSP, CMS Signed Data, CMS Enveloped Data).

**Comment by diafygi** [comment]
I believe offering simple examples of direct WebCryptoAPI usage is useful to learning about the API and what primitives are included. This repo's scope is not to replace PKI / CMS data.
